blank_issues_enabled: false
contact_links:
  - name: 🤔 Feature Requests & Questions 
    url: https://github.com/coltor-apps/basebuilder/discussions
  - name: 💬 New Updates (X)
    url: https://twitter.com/sandulat
    about: Stay up to date with Basebuilder news on X
